name: SkriptBE
main: Skript\SkriptMain
version: 1.5.0
api: 5.0.0
authors: [DominixZ, skyss0fly-pm-pl]
webside: https://github.com/skyss0fly-pm-pl/SkriptBE 
description: Port version of Bukkit Skript for PocketMine-MP

commands:
    skript:
        description: "main command of plugin SkriptBE"
        permission: SkriptBE.skript
        default: false

permissions:
 SkriptBE.skript:
  default: op
  description: "utilise the skript command"
