name: Skript
main: Skript\SkriptMain
version: 1.6.0
api: 5.0.0
author: Zonasky
webside: https://github.com/Zonasky/Skript 
description: Port version of Bukkit Skript for PocketMine-MP

commands:
    skript:
        description: "main command of plugin SkriptBE"
        permission: Skript.skript
        default: false

permissions:
 Skript.skript:
  default: op
  description: "utilise the skript command"
